---
title: "Final Project Code Replication"
author: "Christopher Cebra, Jerome Freudenberg"
date: "3/8/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code Replication
```{r create no signal data}
set.seed(123)
n = 100
d = 100
Xtrain = matrix( rnorm(n*(d+1),mean=0,sd=1), n, (d+1))
Xtrain[,(d+1)] = sign(Xtrain[,(d+1)])
Xholdout = matrix( rnorm(n*(d+1),mean=0,sd=1), n, (d+1))
Xholdout[,(d+1)] = sign(Xholdout[,(d+1)])
Xtest = matrix( rnorm(n*(d+1),mean=0,sd=1), n, (d+1))
Xtest[,(d+1)] = sign(Xtest[,(d+1)])
```

```{r create high signal data}
nbiased = 20
bias = 6/sqrt(n)

Xhstrain = matrix( rnorm(n*(d+1),mean=0,sd=1), n, (d+1))
Xhstrain[,(d+1)] = sign(Xhstrain[,(d+1)])
Xhsholdout = matrix( rnorm(n*(d+1),mean=0,sd=1), n, (d+1))
Xhsholdout[,(d+1)] = sign(Xhsholdout[,(d+1)])
Xhstest = matrix( rnorm(n*(d+1),mean=0,sd=1), n, (d+1))
Xhstest[,(d+1)] = sign(Xhstest[,(d+1)])
b = numeric(n)
for (i in 1:n){
  b[0:nbiased] = bias*Xholdout[i,d+1]
  Xhsholdout = Xhsholdout + b
  b[0:nbiased] = bias*Xtrain[i,d+1]
  Xhstrain = Xhstrain + b
  b[0:nbiased] = bias*Xtest[i,d+1]
  Xhstest = Xhstest + b
}
```