---
title: "STAT 27850 Project 1"
header-includes:
  - \usepackage{soul}
  - \usepackage{xcolor}
  - \usepackage{titlesec}
  - \DeclareMathOperator*{\argmin}{argmin}
output:
  pdf_document: default
geometry:
- margin=1 in
- top=  0.9cm
fontsize: 10pt 
---
```{r global-options, include=FALSE}
knitr::opts_chunk$set(
        fig.width=5, fig.height=3.4,
        fig.path='Figs/', fig.align='center',
        warning=FALSE, message=FALSE,
        strip.white=TRUE, cache=TRUE)
```
\newcommand{\h}[1]{\colorbox{yellow}{$\displaystyle #1$}} 
\titlespacing{\title}{0pt}{\parskip}{-\parskip}    
\vspace{-12.5truemm} 
 
\begin{center}
Christopher Tang
\end{center}


**1**
\small
```{r, eval = TRUE}
library(dplyr)
library(ggplot2)
load("data/bikedata.RData")
bikenum <- as.data.frame(bikenum); day_of_week <- as.data.frame(day_of_week)
duration <- as.data.frame(duration); member <- as.data.frame(member)
station_end <- as.data.frame(station_end); station_start <- as.data.frame(station_start)
days_since_Jan1_2010 <- as.data.frame(days_since_Jan1_2010)
data <- cbind(station_start,station_end,duration,member,bikenum,day_of_week,days_since_Jan1_2010 )
data$ridename <- paste(station_start,' - ',station_end)
data <- add_count(data,station_start,station_end)

```

```{r}
weather <- read.csv("WeatherData.csv")
data <- left_join(data,weather,by='days_since_Jan1_2010')
```
\normalsize
   \emph{(a)}     
       
\small
```{r, eval = TRUE}

```
\normalsize



\small
```{r, eval = TRUE}

```
\normalsize   


```{r}
# top ride
df <- data[data$station_start==31104 & data$station_end==31106,] %>%
  group_by(days_since_Jan1_2010) %>%
  summarize(mean_daily_duration = mean(duration), count=n(), day_of_week=day_of_week, member=member)

ggplot(data=df, aes(x=days_since_Jan1_2010, y=mean_daily_duration)) +
  geom_line() + ylim(c(0,1000))

```

```{r}
routes <- data[data$n > 1000,][,c('station_start', 'station_end')] %>% distinct()
route_pvals <- rep(NA, nrow(routes))
route_coef <- rep(NA, nrow(routes))
for (r in 1:nrow(routes)) {
  fit <- lm(duration ~ days_since_Jan1_2010 + day_of_week + member + TMAX + PRCP,
     data=data[data$station_start==routes[r,]$station_start & data$station_end==routes[r,]$station_end,])
  pval <- summary(fit)$coefficients[,4]['days_since_Jan1_2010']
  coef <- summary(fit)$coefficients[,1]['days_since_Jan1_2010']
  route_pvals[r] <- pval
  route_coef[r] <- coef
}
```

```{r}
# routes w/ p val lower 0.05/1000
print(routes[which(route_pvals < 0.05/1000),])

print(route_coef[which(route_pvals < 0.05/1000)])
# stations[stations[,1] == 31011]
# stations[stations[,1] == 31007]
# stations[stations[,1] == 31217]
# stations[stations[,1] == 31235]
# stations[stations[,1] == 31200]
# stations[stations[,1] == 31225]
```

```{r}
df <- data[data$station_start==31200 & data$station_end==31225,] %>%
  group_by(days_since_Jan1_2010) %>%
  summarize(mean_daily_duration = mean(duration), count=n(), day_of_week=day_of_week, member=member)

ggplot(data=df, aes(x=days_since_Jan1_2010, y=mean_daily_duration)) +
  geom_line() #+ ylim(c(0,5000))
```



       
